### ISSUE TITLE
Extending partition vignette -- inter_item_reliability()

### ISSUE THREAD

**Issue by millstei** [USCbiostats/partition#27]
It looks like the function, inter_item_reliability(), in the "Extending partition" vignette computes the overall mean of correlations between all pairs of features including correlations between each feature and itself, which is always 1 of course. Shouldn't the mean exclude these 1's, that is, just take the upper or lower triangle of the correlation matrix?

```{r}
# Test inter_item_reliability()
inter_item_reliability <- function(.data) {
  corr(.data) %>%
    colMeans(na.rm = TRUE) %>%
    mean()
}
n = 1000
m = 3
mat = matrix(rnorm(n*m), ncol=m)
inter_item_reliability(mat)
# this result is > 0.3 even though features are completely independent
```

**Comment by malcolmbarrett** [comment]
Yeah, I guess it should be something like 

```r
inter_item_reliability <- function(mat) {
  corrs <- corr(mat)
  corrs[lower.tri(corrs, diag = TRUE)] <- NA
  
  corrs %>%
    colMeans(na.rm = TRUE) %>%
    mean(na.rm = TRUE)
}
```
